---
- hosts: lb
  sudo: yes
  roles:
    - ganglia-server

- hosts: web
  sudo: yes
  roles:
    - ganglia-client

- hosts: lb
  sudo: yes
  roles:
    - lb

- hosts: web
  sudo: yes
  roles:
    - tomcat-setup
  serial: 1
  pre_tasks:
    - name: disable server in haproxy
      shell: echo "disable server poc/{{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
      delegate_to: "{{ item }}"
      with_items: groups.lb
      

    
  post_tasks:
    - name: enable server in haproxy
      shell: echo "enable server poc/{{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
      delegate_to: "{{ item }}"
      with_items: groups.lb
