---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: webservers
  sudo: yes
  roles:
    - tomcat7
    - ganglia-client

- hosts: ganglia-server
  sudo: yes
  roles:
    - ganglia-server

