---
- name: Install Java 
  apt: name=openjdk-7-jre update_cache=yes state=present

- name: install tomcat
  apt: name=tomcat7 update_cache=yes state=present

- name: Deploy app 
  copy: src=java-app/SpringMVCSecurityXML/target/SpringMVCSecurityXML.war dest=/var/lib/tomcat7/webapps/SpringMVCSecurityXML.war
  notify: 
  - Restart Tomcat
